before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs curl sudo
  - curl https://install.meteor.com/ | sh
  - meteor npm install --save @babel/runtime
  - meteor npm install --save simpl-schema

rspec:
  script:
    - meteor --allow-superuser --raw-logs --settings settings.json